### ISSUE TITLE
Default geogrid SST interpolation problem

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/WPS#1]
ERA5 land-sea mask is clearly visible along the coastlines using the default interpolation. E.g. for T2:

![image](https://github.com/FPS-URB-RCC/WPS/assets/8810015/9cfaea9d-caf6-4a32-9218-1e32922255a7)

**Comment by yoselita** [comment]
In the default METGRID.TBL.ARW interpolation options for SST are sixteen_pt+four_pt. By adding additional interpolation options (i.e. wt_average_4pt+wt_average_16pt+search) to the the default ones, and by masking the land, the weird pattern related to SST disappears. 
The figure bellow shows SST from a met_em file, in the left is the default one, and in the right is the one with changed METGRID.TBL.ARW:

![image](https://github.com/FPS-URB-RCC/WPS/assets/54983612/83ad37b5-e4eb-4aca-80ef-46165ae1a7df)


This figure shows the same timestep for T2 as above from a wrfout file after applying the metgrid fix: 

![image](https://github.com/FPS-URB-RCC/WPS/assets/54983612/93c8f283-c126-4301-89ef-8bae021e440d)
